version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      - cache
    networks:
      - app-net

  cache:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - app-net

networks:
  app-net:
# Even though Caffeine is in-memory, I added Redis here in case I want to switch later.
